import { Category } from "./types/types";

export const catImages = [
  {
    id: 1,
    image: "/categories/tisane-detox.webp",
    title: "Tisane Detox",
    slug: "tisane-detox",
  },
  {
    id: 2,
    image: "/categories/savonnette.webp",
    title: "Savon",
    slug: "savon",
  },
  {
    id: 3,
    image: "/categories/tisane-digestive.webp",
    title: "Tisane Digestive",
    slug: "tisane-digestive",
  },
  {
    id: 4,
    image: "/categories/baume-a-barbe.webp",
    title: "Baume à Barbe",
    slug: "baume-barbe",
  },
  {
    id: 5,
    image: "/categories/cheveux.webp",
    title: "Cheveux",
    slug: "cheveux",
  },
  {
    id: 6,
    image: "/categories/huile-a-barbe.webp",
    title: "Huile à Barbe",
    slug: "huile-a-barbe",
  },
];

export const categories: Category[] = [
  {
    title: "Tisane detox",
    slug: "tisane-detox",
    id: "hnjs12k",
  },
  {
    title: "Tisane digestive",
    slug: "tisane-digestive",
    id: "kjb29lr",
  },
  {
    title: "Huile a barbe",
    slug: "huile-a-barbe",
    id: "pacf9l4",
  },
  {
    title: "Baume à barbe",
    slug: "baume-barbe",
    id: "gyg6k6h",
  },
  {
    title: "Savon",
    slug: "savon",
    id: "mb13w3q",
    subcategories: [
      {
        title: "Op",
        slug: "op",
        id: "yfb74l7",
      },
      {
        title: "Huile",
        slug: "huile",
        id: "hiuan5y",
      },
    ],
  },
];

export const products = [
  {
    id: 1,
    title:
      "Nuhanciam Lait Corps Éclaircissant Taches et Hydratant correcteur d’Hyperpigmentation 500 ml",
    slug: "nuhanciam-lait-corps-eclaircissant-taches-et-hydratant-correcteur-d-hyperpigmentation-500-ml",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
  {
    id: 2,
    title: "Produit  de detox pour enlever des toxines",
    slug: "produit-de-detox-pour-enlever-des-toxines",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
  {
    id: 3,
    title:
      "Nuhanciam Lait Corps Éclaircissant Taches et Hydratant correcteur d’Hyperpigmentation 500 ml",
    slug: "nuhanciam-lait-corps-eclaircissant-taches-et-hydratant-correcteur-d-hyperpigmentation-500-ml",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
  {
    id: 4,
    title: "Produit  de detox pour enlever des toxines",
    slug: "produit-de-detox-pour-enlever-des-toxines",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
  {
    id: 5,
    title: "Produit  de detox pour enlever des toxines",
    slug: "produit-de-detox-pour-enlever-des-toxines",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
  {
    id: 6,
    title: "Produit  de detox pour enlever des toxines",
    slug: "produit-de-detox-pour-enlever-des-toxines",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
  {
    id: 7,
    title: "Produit  de detox pour enlever des toxines",
    slug: "produit-de-detox-pour-enlever-des-toxines",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
  {
    id: 8,
    title: "Produit  de detox pour enlever des toxines",
    slug: "produit-de-detox-pour-enlever-des-toxines",
    description: "Description du produit 1",
    price: 2175,
    benefits: [
      "Unifie le teint",
      "Corrige et prévient l’apparition des taches",
      "Protection SPF15 (UVA/UVB)",
      "Hydratation intense 24h",
    ],
    discountPrice: 3575,
    productImage: "/products/timex.jpg",
    stock: 10,
    brand: "ToipDetox",
    sku: "12345",
    etiquette: "Detox",
  },
];


export const currentSelection = [
  {
    id: "hsy51",
    title: "Tisane detox",
    description: "Tisane detox prepare avec soin pour enlever des toxines",
    category: "tisane-detox",
    productImage: "/current/tisane-detox.webp",
    isActive: true,
  },
  {
    id: "atw92",
    title: "Tisane digestive",
    description: "Produit de tisane digestive pour enlever des toxines",
    category: "tisane-digestive",
    productImage: "/current/tisane-digestive.webp",
    isActive: false,
  },
  {
    id: "xqy73",
    title: "Jus de tisane detox",
    description: "Jus de tisane detox prepare avec soin pour enlever des toxines",
    category: "tisane-detox",
    productImage: "/current/tisane.webp",
    isActive: false,
  },
];
